version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "ryankanno"
    commit-message:
      prefix: build(github)
    labels:
      - "github-actions"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "ryankanno"
    commit-message:
      prefix: build
      include: scope
    open-pull-requests-limit: 10
    labels:
      - "automerge"
      - "pip"
      - "dependencies"
