---
default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-added-large-files
  - repo: https://github.com/ansible/ansible-lint
    rev: v5.3.1
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        additional_dependencies:
          - ansible>=2.10,<2.11  # or use ansible-base if you want the slim version
          - yamllint>=1.25.0,<2.0.  # this enables YAML support
