---
  language: python
  python: "2.7"
  sudo: false
  addons:
    apt:
      packages:
        - python-apt
        - python-pycurl
  install:
    - pip install ansible
  script:
    - echo localhost > inventory
    - ansible-playbook -i inventory --syntax-check site.yml
