---
  - hosts: devmachine
    roles:
      - role: anyenv
      - role: bash_it
      - { role: development, ignore_errors: yes }
      - role: geerlingguy.homebrew  
      - role: dotfiles
      - role: vim
        #- role: pyenv
        #when: "'pyenv' in anyenv.environments"
        #- role: rbenv
        #when: "'rbenv' in anyenv.environments"
      - role: dock
        when: "ansible_distribution == 'MacOSX'"
      - role: finder
        when: "ansible_distribution == 'MacOSX'"
