---
  - hosts: devmachine
    roles:
      - role: anyenv
      - role: bash_it
      - role: development
      - role: dotfiles
      - role: vim
      - role: pyenv
        when: "'pyenv' in anyenv.environments"
      - role: rbenv
        when: "'rbenv' in anyenv.environments"
      - role: dock
        when: "ansible_distribution == 'MacOSX'"
      - role: finder
        when: "ansible_distribution == 'MacOSX'"
