---
  - hosts: devmachine
    sudo: yes
    roles:
      - development
      - dotfiles
      - anyenv
      - { role: pyenv, when: "'pyenv' in anyenv.environments" }
      - { role: rbenv, when: "'rbenv' in anyenv.environments" }
      - bashmarks
      - { role: dock, when: "ansible_distribution == 'MacOSX'" }
      - { role: finder, when: "ansible_distribution == 'MacOSX'" }
