---
  - hosts: devmachine
    sudo: yes
    roles:
      - development
      - dotfiles
      - anyenv
      - { role: dock, when: "ansible_distribution == 'MacOSX'" }
      - { role: finder, when: "ansible_distribution == 'MacOSX'" }
