---
- hosts: devmachine
  roles:
    - role: anyenv
    - role: bash_it
    - role: development
      ignore_errors: yes
      tags:
        - development
    - role: dotfiles
    - role: vim
      tags:
        - vim
    - role: pyenv
      when: "'pyenv' in anyenv.environments"
    - role: rbenv
      when: "'rbenv' in anyenv.environments"
    - role: nodenv
      when: "'nodenv' in anyenv.environments"
    - role: geerlingguy.mac.homebrew
      ignore_errors: yes
      tags:
        - homebrew
      when: "ansible_distribution == 'MacOSX'"
    - role: geerlingguy.mac.mas
      ignore_errors: yes
      tags:
        - mas
      when: "ansible_distribution == 'MacOSX'"
    - role: dock
      when: "ansible_distribution == 'MacOSX'"
    - role: finder
      when: "ansible_distribution == 'MacOSX'"
