---
- name: dotfiles | chezmoi | init chezmoi
  command: chezmoi init {{ dotfiles.chezmoi.repo.git_url }}
  tags:
    - dotfiles
    - chezmoi

- name: dotfiles | chezmoi | apply dotfiles
  command: chezmoi apply
