---
  - name: dotfiles | rcm | ensure rcm is installed
    stat: path={{ dotfiles.rcm.rcup_path }}
    register: rcm_installed

  - name: dotfiles | rcm | ensure git is installed
    stat: path={{ dotfiles.git.git_path }}
    register: git_installed

  - name: dotfiles | rcm | get dotfiles repo
    git: repo={{ dotfiles.rcm.repo.name }} dest={{ dotfiles.install_dir }} version={{ dotfiles.rcm.repo.version }}
    when: rcm_installed and git_installed

  - name: dotfiles | rcm | install dotfiles submodules
    command : cd {{ dotfiles.install_dir }} && git submodule init && git submodule update
    when: rcm_installed and git_installed

  - name: dotfiles | rcm | install dotfiles to be managed by rcm
    command: "{{ dotfiles.rcm.rcup_path }} -f -d {{ dotfiles.install_dir }}"
