---
- name: dock | main | remove persistent-apps
  community.general.osx_defaults:
    domain: com.apple.dock
    key: persistent-apps
    state: absent
  when: dock is defined and dock.persistent_apps is defined
  tags:
    - dock

- name: dock | main | remove persistent-others
  community.general.osx_defaults:
    domain: com.apple.dock
    key: persistent-others
    state: absent
  when: dock is defined and dock.persistent_others is defined
  tags:
    - dock

- name: dock | main | insert persistent-apps
  command: defaults write com.apple.dock persistent-apps -array-add "<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>{{ item }}</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>"  # noqa: yaml
  with_items: "{{ dock.persistent_apps }}"
  when: dock is defined and dock.persistent_apps is defined
  tags:
    - dock

- name: dock | main | enable animations
  community.general.osx_defaults:
    domain: com.apple.finder
    key: DisableAllAnimations
    type: bool
    value: false
    state: present
  tags:
    - dock

- name: dock | main | enable autohide
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true
  tags:
    - dock

- name: dock | main | load smaller icons
  community.general.osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: integer
    value: 48
  tags:
    - dock

- name: dock | main | set on left side
  community.general.osx_defaults:
    domain: com.apple.dock
    key: orientation
    type: string
    value: left
  tags:
    - dock

- name: dock | main | kill dock
  command: /usr/bin/killall Dock
  when: dock is defined and (dock.persistent_apps is defined or dock.persistent_others is defined)
  tags:
    - dock
