---
  - name: anyenv | main | install anyenv from git repo
    git: repo="{{ anyenv.git_url }}" dest="{{ anyenv.install_dir }}"
    tags:
      - anyenv

  - name: anyenv | main | install anyenv environments
    command: eval "$(anyenv init -)"; anyenv install {{ item.environment }} creates={{ anyenv.install_dir }}/envs/{{ item.environment }}
    with_items:
      - "{{ anyenv.environments }}"
    tags:
      - anyenv

  - name: anyenv | main | install specific environment versions
    shell: eval "$(anyenv init -)"; {{ item.0.environment }} install {{ item.1 }} creates={{ anyenv.install_dir }}/envs/{{ item.0.environment }}/versions/{{ item.1 }}
    with_subelements:
      - "{{ anyenv.environments }}"
      - versions
    tags:
      - anyenv
