---
  - name: package_installer_osmacosx | install macports packages
    macports: name={{ item }} state=present
    with_items: macports_packages
    environment: env.proxies
    tags:
      - macports
    when: macports_packages is defined

  - name: package_installer_osmacosx | install homebrew packages
    homebrew: name={{ item }} state=present
    with_items: homebrew_packages
    environment: env.proxies
    tags:
      - homebrew
    when: homebrew_packages is defined
