---
  - name: development | package_installer_os_macosx | install macports packages
    macports: name={{ item }} state=present
    with_items: "{{ macports_packages }}"
    environment: env
    become: yes
    tags:
      - macports
    when: macports_packages is defined
