---
  - name: vim | main | ensure git is installed
    debug:
      msg: "TODO"

  - name: vim | main | install vimrc
    shell: curl -o - https://raw.githubusercontent.com/ryankanno/vim-config/master/install.sh | bash creates=~/.vim-config
