---
  - name: bashmarks | main | clone bashmarks from git repo
    git: repo="{{ bashmarks.git_url }}" dest="{{ bashmarks.install_dir }}"
    tags:
      - bashmarks

  - name: bashmarks | main | install bashmarks
    command: make install
    args:
      chdir: "{{ bashmarks.install_dir }}"
      creates: ~/.local
    tags:
      - bashmarks
