name: "ansible-lint"

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup environment
        run: |
          ansible-galaxy install -r requirements.yml

      - name: "lint ansible playbook"
        uses: ansible/ansible-lint-action@master
        with:
          targets: "*.yml"
          override-deps: |
            ansible-lint==5.3.1
          args: -c .ansible-lint
